:toc: left
:toclevels: 5
:sectnums:

= テスト駆動開発から始めるRuby入門

これはとあるプログラマがどのような思考を経てテスト駆動開発でアプリケーションを構築していったかを解説した内容である。隣りに座って話を聞きながらコードを追いかけているイメージで読み進めてみてださい。

== エピソード1
include::episode_1.adoc[]

== エピソード2
include::episode_2.adoc[]

== エピソード3
=== オブジェクト指向から始めるテスト駆動開発
仕様

  1 から 100 までの数をプリントするプログラムを書け。
  ただし 3 の倍数のときは数の代わりに｢Fizz｣と、5 の倍数のときは｢Buzz｣とプリントし、
  3 と 5 両方の倍数の場合には｢FizzBuzz｣とプリントすること。
  タイプごとに出力を切り替えることができる。
  タイプ１は通常、タイプ２は数字のみ、タイプ３は FizzBuzz の場合のみをプリントする。

[source, bash]
----
$ rake
----

==== TODOリスト作成
TODOリスト

* タイプ1の場合
** 数を文字列にして返す
*** 1を渡したら文字列"1"を返す

==== タイプ1の場合
[source, ruby]
----
...
  end

  describe 'タイプごとに出力を切り替えることができる' do
    describe 'タイプ1の場合' do
      def test_1を渡したら文字列1を返す
        assert_equal '1', FizzBuzz.generate(1, 1)
      end
    end
  end

  describe '配列や繰り返し処理を理解する' do
...
----

[source, bash]
----
05:32:51 - INFO - Running: all tests
Coverage report generated for MiniTest to /workspace/tdd_rb/coverage. 4 / 11 LOC (36.36%) covered.
Started with run options --guard --seed 37049

ERROR["test_1を渡したら文字列1を返す", #<Minitest::Reporters::Suite:0x00005623e6a24260 @name="タイプごとに出力を切り替えることができる::タイプ1の場合">, 0.0019176720088580623]
 test_1を渡したら文字列1を返す#タイプごとに出力を切り替えることができる::タイプ1の場合 (0.00s)
Minitest::UnexpectedError:         ArgumentError: wrong number of arguments (given 2, expected 1)
            /workspace/tdd_rb/lib/fizz_buzz.rb:6:in `generate'
            /workspace/tdd_rb/test/fizz_buzz_test.rb:74:in `test_1を渡したら文字列1を返す'

  25/25: [=================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.00796s
25 tests, 26 assertions, 0 failures, 1 errors, 0 skips
----

[source, bash]
----
...
class FizzBuzz
  MAX_NUMBER = 100

  def self.generate(number, _type = 1)
    is_fizz = number.modulo(3).zero?
    is_buzz = number.modulo(5).zero?

    return 'FizzBuzz' if is_fizz && is_buzz
    return 'Fizz' if is_fizz
    return 'Buzz' if is_buzz

    number.to_s
  end
...
----

[source, bash]
----
05:32:52 - INFO - Inspecting Ruby code style: test/fizz_buzz_test.rb Guardfile
 2/2 files |====================================== 100 =======================================>| Time: 00:00:00 

2 files inspected, no offenses detected
05:32:54 - INFO - Inspecting Ruby code style: coverage/assets/0.10.2/colorbox/loading_background.png coverage/assets/0.10.2/colorbox/controls.png coverage/assets/0.10.2/colorbox/loading.gif coverage/assets/0.10.2/colorbox/border.png
 0/0 files |====================================== 100 =======================================>| Time: 00:00:00 

0 files inspected, no offenses detected
05:37:29 - INFO - Inspecting Ruby code style: lib/fizz_buzz.rb
lib/fizz_buzz.rb:6:29: W: [Corrected] Lint/UnusedMethodArgument: Unused method argument - type. If it's necessary, use _ or _type as an argument name to indicate that it won't be used.
  def self.generate(number, type = 1)
                            ^^^^
 1/1 file |======================================= 100 =======================================>| Time: 00:00:00 

1 file inspected, 1 offense detected, 1 offense corrected
05:37:31 - INFO - Inspecting Ruby code style: lib/fizz_buzz.rb
 1/1 file |======================================= 100 =======================================>| Time: 00:00:00 

1 file inspected, no offenses detected
[1] guard(main)> 
05:39:37 - INFO - Run all
05:39:37 - INFO - Running: all tests
Coverage report generated for MiniTest to /workspace/tdd_rb/coverage. 4 / 11 LOC (36.36%) covered.
Started with run options --guard --seed 8607

  25/25: [=================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.00723s
25 tests, 27 assertions, 0 failures, 0 errors, 0 skips
...
----

[source, ruby]
----
...
class FizzBuzz
  MAX_NUMBER = 100

  def self.generate(number, type = 1)
    case type
    when 1
      is_fizz = number.modulo(3).zero?
      is_buzz = number.modulo(5).zero?

      return 'FizzBuzz' if is_fizz && is_buzz
      return 'Fizz' if is_fizz
      return 'Buzz' if is_buzz

      number.to_s
    end
  end
...
----

[source, bash]
----
1] guard(main)> 
06:00:10 - INFO - Run all
06:00:10 - INFO - Running: all tests
Coverage report generated for MiniTest to /workspace/tdd_rb/coverage. 4 / 12 LOC (33.33%) covered.
Started with run options --guard --seed 3988

  25/25: [=================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.00756s
25 tests, 27 assertions, 0 failures, 0 errors, 0 skips

06:00:11 - INFO - Inspecting Ruby code style of all files
 7/7 files |====================================== 100 =======================================>| Time: 00:00:00 

7 files inspected, no offenses detected
06:00:12 - INFO - Inspecting Ruby code style: coverage/assets/0.10.2/colorbox/loading_background.png coverage/assets/0.10.2/colorbox/controls.png coverage/assets/0.10.2/colorbox/loading.gif coverage/assets/0.10.2/colorbox/border.png
 0/0 files |====================================== 100 =======================================>| Time: 00:00:00 

0 files inspected, no offenses detected
----

[source, bash]
----
$ git add .
$ git commit -m 'test: タイプ1の場合'
----

[source, ruby]
----
...

class FizzBuzzTest < Minitest::Test
  describe '数を文字列にして返す' do
    describe 'タイプ1の場合' do
      def setup
        @fizzbuzz = FizzBuzz
      end

      describe '三の倍数の場合' do
        def test_3を渡したら文字列Fizzを返す
          assert_equal 'Fizz', @fizzbuzz.generate(3)
        end
      end

      describe '五の倍数の場合' do
        def test_5を渡したら文字列Buzzを返す
          assert_equal 'Buzz', @fizzbuzz.generate(5)
        end
      end

      describe '三と五の倍数の場合' do
        def test_15を渡したら文字列FizzBuzzを返す
          assert_equal 'FizzBuzz', @fizzbuzz.generate(15)
        end
      end

      describe 'その他の場合' do
        def test_1を渡したら文字列1を返す
          assert_equal '1', @fizzbuzz.generate(1)
        end
      end

      describe '1から100までのFizzBuzzの配列を返す' do
        def setup
          @result = FizzBuzz.generate_list
        end

        def test_配列の初めは文字列の1を返す
          assert_equal '1', @result.first
        end

        def test_配列の最後は文字列のBuzzを返す
          assert_equal 'Buzz', @result.last
        end

        def test_配列の2番目は文字列のFizzを返す
          assert_equal 'Fizz', @result[2]
        end

        def test_配列の4番目は文字列のBuzzを返す
          assert_equal 'Buzz', @result[4]
        end

        def test_配列の14番目は文字列のFizzBuzzを返す
          assert_equal 'FizzBuzz', @result[14]
        end
      end
    end
  end
...
----

[source, bash]
----
$ git add .
$ $ git commit -m 'refactor: メソッドのインライン化'
----

TODOリスト

* タイプ1の場合
** 数を文字列にして返す
*** [line-through]_1を渡したら文字列"1"を返す_
** 3 の倍数のときは数の代わりに｢Fizz｣と返す_
*** [line-through]_3を渡したら文字列"Fizz"を返す_
** 5 の倍数のときは｢Buzz｣と返す_
*** [line-through]_5を渡したら文字列"Buzz"を返す_
** 3 と 5 両方の倍数の場合には｢FizzBuzz｣と返す_
*** [line-through]_15を渡したら文字列"FizzBuzz"を返す_
* タイプ2の場合
** 数を文字列にして返す
*** 1を渡したら文字列"1"を返す
** 3 の倍数のときは数を文字列にして返す
*** 3を渡したら文字列"3"を返す
** 5 の倍数のときは数を文字列にして返す
*** 5を渡したら文字列"5"を返す
** 3 と 5 両方の倍数の場合には数を文字列にして返す
*** 15を渡したら文字列"15"を返す
* タイプ3の場合
** 数を文字列にして返す
*** 1を渡したら文字列"1"を返す
** 3 の倍数のときは数を文字列にして返す
*** 3を渡したら文字列"3"を返す
** 5 の倍数のときは数を文字列にして返す
*** 5を渡したら文字列"5"を返す
** 3 と 5 両方の倍数の場合には｢FizzBuzz｣と返す
*** 15を渡したら文字列"FizzBuzz"を返す

==== タイプ2の場合
TODOリスト

* [line-through]_タイプ1の場合_
* タイプ2の場合
** 数を文字列にして返す
*** 1を渡したら文字列"1"を返す
** 3 の倍数のときは数を文字列にして返す
*** 3を渡したら文字列"3"を返す
** 5 の倍数のときは数を文字列にして返す
*** 5を渡したら文字列"5"を返す
** 3 と 5 両方の倍数の場合には数を文字列にして返す
*** 15を渡したら文字列"15"を返す
* タイプ3の場合
** 数を文字列にして返す
*** 1を渡したら文字列"1"を返す
** 3 の倍数のときは数を文字列にして返す
*** 3を渡したら文字列"3"を返す
** 5 の倍数のときは数を文字列にして返す
*** 5を渡したら文字列"5"を返す
** 3 と 5 両方の倍数の場合には｢FizzBuzz｣と返す
*** 15を渡したら文字列"FizzBuzz"を返す

[source, ruby]
----
...
    end

    describe 'タイプ2の場合' do
      def setup
        @fizzbuzz = FizzBuzz
      end

      describe 'その他の場合' do
        def test_1を渡したら文字列1を返す
          assert_equal '1', @fizzbuzz.generate(1, 2)
        end
      end
    end
...
----

[source, bash]
----
...
FAIL["test_1を渡したら文字列1を返す", #<Minitest::Reporters::Suite:0x00005555ec747100 @name="数を文字列にして返す::タイプ2の場合::その他の場合">, 0.002283181995153427]
 test_1を渡したら文字列1を返す#数を文字列にして返す::タイプ2の場合::その他の場合 (0.00s)
        Expected: "1"
          Actual: nil
        /workspace/tdd_rb/test/fizz_buzz_test.rb:75:in `test_1を渡したら文字列1を返す'

  24/24: [=================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.00437s
24 tests, 26 assertions, 1 failures, 0 errors, 0 skips
...
----

[source, ruby]
----
...
class FizzBuzz
  MAX_NUMBER = 100

  def self.generate(number, type = 1)
    case type
    when 1
      is_fizz = number.modulo(3).zero?
      is_buzz = number.modulo(5).zero?

      return 'FizzBuzz' if is_fizz && is_buzz
      return 'Fizz' if is_fizz
      return 'Buzz' if is_buzz

      number.to_s
    when 2
      number.to_s
    end
  end
...
----

[source, bash]
----
[1] guard(main)> 
06:21:44 - INFO - Run all
06:21:44 - INFO - Running: all tests
Coverage report generated for MiniTest to /workspace/tdd_rb/coverage. 4 / 13 LOC (30.77%) covered.
Started with run options --guard --seed 29302

  24/24: [=================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.00453s
24 tests, 26 assertions, 0 failures, 0 errors, 0 skips
...
----

[source, ruby]
----
...
   end

    describe 'タイプ2の場合' do
      def setup
        @fizzbuzz = FizzBuzz
      end

      describe '三の倍数の場合' do
        def test_3を渡したら文字列3を返す
          assert_equal '3', @fizzbuzz.generate(3, 2)
        end
      end

      describe '五の倍数の場合' do
        def test_5を渡したら文字列5を返す
          assert_equal '5', @fizzbuzz.generate(5, 2)
        end
      end

      describe '三と五の倍数の場合' do
        def test_15を渡したら文字列15を返す
          assert_equal '15', @fizzbuzz.generate(15, 2)
        end
      end

      describe 'その他の場合' do
        def test_1を渡したら文字列1を返す
          assert_equal '1', @fizzbuzz.generate(1, 2)
        end
      end
    end
  end
...
----

[source, bash]
----
...
Coverage report generated for MiniTest to /workspace/tdd_rb/coverage. 4 / 13 LOC (30.77%) covered.
Started with run options --guard --seed 898

  27/27: [=================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.00900s
27 tests, 29 assertions, 0 failures, 0 errors, 0 skips

06:27:40 - INFO - Inspecting Ruby code style of all files
test/fizz_buzz_test.rb:11:3: C: Metrics/BlockLength: Block has too many lines. [70/62]                          
  describe '数を文字列にして返す' do ...
  ^^^^^^^^^^^^^^^^^^^^^^^^
 7/7 files |====================================== 100 =======================================>| Time: 00:00:00 

7 files inspected, 1 offense detected
...
----

[source, yml]
----
...
# Offense count: 2
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 62
  Exclude:
    - 'test/fizz_buzz_test.rb'
...
----

[source, bash]
----
[1] guard(main)> 
06:33:03 - INFO - Run all
06:33:03 - INFO - Running: all tests
Coverage report generated for MiniTest to /workspace/tdd_rb/coverage. 4 / 13 LOC (30.77%) covered.
Started with run options --guard --seed 42496

  27/27: [=================================================================] 100% Time: 00:00:00, Time: 00:00:00

Finished in 0.00824s
27 tests, 29 assertions, 0 failures, 0 errors, 0 skips

06:33:03 - INFO - Inspecting Ruby code style of all files
 7/7 files |====================================== 100 =======================================>| Time: 00:00:00 

7 files inspected, no offenses detected
06:33:05 - INFO - Inspecting Ruby code style: coverage/assets/0.10.2/colorbox/loading_background.png coverage/assets/0.10.2/colorbox/controls.png coverage/assets/0.10.2/colorbox/loading.gif coverage/assets/0.10.2/colorbox/border.png
 0/0 files |====================================== 100 =======================================>| Time: 00:00:00 

0 files inspected, no offenses detected
----

[source, bash]
----
$ git add .
$ git commit -m 'test: タイプ2の場合'
----

TODOリスト

* [line-through]_タイプ1の場合_
* タイプ2の場合
** 数を文字列にして返す
*** [line-through]_1を渡したら文字列"1"を返す_
** 3 の倍数のときは数を文字列にして返す
*** [line-through]_3を渡したら文字列"3"を返す_
** 5 の倍数のときは数を文字列にして返す
*** [line-through]_5を渡したら文字列"5"を返す_
** 3 と 5 両方の倍数の場合には数を文字列にして返す
*** [line-through]_15を渡したら文字列"15"を返す_
* タイプ3の場合
** 数を文字列にして返す
*** 1を渡したら文字列"1"を返す
** 3 の倍数のときは数を文字列にして返す
*** 3を渡したら文字列"3"を返す
** 5 の倍数のときは数を文字列にして返す
*** 5を渡したら文字列"5"を返す
** 3 と 5 両方の倍数の場合には｢FizzBuzz｣と返す
*** 15を渡したら文字列"FizzBuzz"を返す

==== タイプ3の場合
==== フィールドのカプセル化
==== ポリモーフィズムによる条件記述の置き換え
==== スーパークラスの抽出
==== オブジェクトによるプリミティブの置き換え
==== アサーションの導入
==== 例外によるエラーコードの置き換え
==== モジュールの分割

== エピソード4
=== クライアント開発から始めるテスト駆動開発
==== APIサービスを作る
==== APIサービスと連携する
==== UIを作る
==== UIとAPIサービスを連携する

== エピソード5
=== 継続的インテグレーションから始めるテスト駆動開発
==== E2Eテストのセットアップ
==== クライアントモジュールの分割
==== 本番環境と開発環境で表示を切り返る
==== クライアントタスクの自動化
==== コードレビュー

== 参照

=== 参考サイト

- https://channel9.msdn.com/Events/de-code/2017/DO03?ocid=player[50 分でわかるテスト駆動開発^]
- https://backlog.com/ja/git-tutorial/[サルでもわかるGit入門〜バージョン管理を使いこなそう〜^]
- https://docs.ruby-lang.org/ja/[プログラミング言語 Ruby リファレンスマニュアル^]
- https://qiita.com/jnchito/items/2dc760ee0716ea12bbf0[検索結果を要チェック！Rubyの公式リファレンスは docs.ruby-lang.org です 〜公式な情報源を調べるクセを付けよう〜^]
- https://t-wada.hatenablog.jp/entry/clean-code-that-works[動作するきれいなコード: SeleniumConf Tokyo 2019 基調講演文字起こし+α]

- https://github.com/rubocop-hq/rubocop[RuboCop]
- https://qiita.com/tomohiii/items/1a17018b5a48b8284a8b[RuboCop is 何？]
- https://qiita.com/abcb2/items/9905449ab3fcf5d27ace[ruby rake の使い方]
- https://qiita.com/tbpgr/items/443fe45f0dbe02aa768a[RuboCopのrake taskを使う]

=== 参考図書

++++
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=qf_sp_asin_til&t=k2works0c-22&m=amazon&o=9&p=8&l=as1&IS1=1&detail=1&asins=4274217884&linkId=568f25b974af5645e862928a12c354e1&bc1=ffffff&lt1=_top&fc1=333333&lc1=0066c0&bg1=ffffff&f=ifr"></iframe>
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=qf_sp_asin_til&t=k2works0c-22&m=amazon&o=9&p=8&l=as1&IS1=1&detail=1&asins=427405019X&linkId=08e705a5969e20f5129b4d3cefbcdb15&bc1=000000&lt1=_top&fc1=333333&lc1=0066c0&bg1=ffffff&f=ifr"></iframe>
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//rcm-fe.amazon-adsystem.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=k2works0c-22&language=ja_JP&o=9&p=8&l=as4&m=amazon&f=ifr&ref=as_ss_li_til&asins=4274224546&linkId=5f857b58e988073ce92e0adcf1dd3ebb"></iframe>
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//rcm-fe.amazon-adsystem.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=k2works0c-22&language=ja_JP&o=9&p=8&l=as4&m=amazon&f=ifr&ref=as_ss_li_til&asins=4873115655&linkId=82416afd8e4042cbfd2dc6d4b80653f1"></iframe>
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//rcm-fe.amazon-adsystem.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=k2works0c-22&language=ja_JP&o=9&p=8&l=as4&m=amazon&f=ifr&ref=as_ss_li_til&asins=4774198617&linkId=7858ddef815d9a093fcacb3a1208b774"></iframe>
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//rcm-fe.amazon-adsystem.com/e/cm?lt1=_blank&bc1=000000&IS2=1&bg1=FFFFFF&fc1=000000&lc1=0000FF&t=k2works0c-22&language=ja_JP&o=9&p=8&l=as4&m=amazon&f=ifr&ref=as_ss_li_til&asins=4774193976&linkId=fee0d915272172c2e25393dd52537bdc"></iframe>
++++

[bibliography]
== References

- [[[tdd, 1]]] テスト駆動開発 Kent Beck (著), 和田 卓人 (翻訳):
  オーム社; 新訳版 (2017/10/14)
- [[[rft, 2]]] 新装版 リファクタリング―既存のコードを安全に改善する― (OBJECT TECHNOLOGY SERIES) Martin Fowler (著), 児玉 公信 (翻訳), 友野 晶夫 (翻訳), 平澤 章  (翻訳), その他:
  オーム社; 新装版 (2014/7/26)
- [[[rft2, 3]]] リファクタリング(第2版): 既存のコードを安全に改善する (OBJECT TECHNOLOGY SERIES) Martin Fowler (著), 児玉 公信 (翻訳), 友野 晶夫 (翻訳), 平澤 章 (翻訳), その他:
  オーム社; 第2版 (2019/12/1)
- [[[rcd, 4]]] リーダブルコード ―より良いコードを書くためのシンプルで実践的なテクニック (Theory in practice) Dustin Boswell (著), Trevor Foucher (著), 須藤 功平 (解説), 角 征典  (翻訳):
  オライリージャパン; 初版八刷版 (2012/6/23)
- [[[kruby, 5]]] かんたん Ruby (プログラミングの教科書) すがわらまさのり  (著)
  技術評論社 (2018/6/21)
- [[[pruby, 6]]] プロを目指す人のためのRuby入門 言語仕様からテスト駆動開発・デバッグ技法まで (Software Design plusシリーズ) 伊藤 淳一  (著):
  技術評論社 (2017/11/25)

