:toc: left
:toclevels: 5
:sectnums:

= Fizz Buzz

== 仕様

1 から 100 までの数をプリントするプログラムを書け。

ただし 3 の倍数のときは数の代わりに｢Fizz｣と、5 の倍数のときは｢Buzz｣とプリントし、

3 と 5 両方の倍数の場合には｢FizzBuzz｣とプリントすること。

タイプごとに出力を切り替えることができる。

タイプ１は通常、タイプ２は数字のみ、タイプ３は FizzBuzz の場合のみをプリントする。

== 設計
=== TODOリスト
- [x] タイプ1の場合
 - [x] 数を文字列にして返す
    - [x] 1を渡したら文字列"1"を返す
    - [x] 2を渡したら文字列"2"を返す
  - [x] 3 の倍数のときは数の代わりに｢Fizz｣と返す
    - [x] 3を渡したら文字列"Fizz"を返す
  - [x] 5 の倍数のときは｢Buzz｣と返す
    - [x] 5を渡したら文字列"Buzz"を返す
  - [x] 3 と 5 両方の倍数の場合には｢FizzBuzz｣と返す
    - [x] 15を渡したら文字列"FizzBuzz"を返す
- [x] タイプ2の場合
  - [x] 数を文字列にして返す
    - [x] 1を渡したら文字列"1"を返す
    - [x] 2を渡したら文字列"2"を返す
  - [x] 3 の倍数のときは数を文字列にして返す
    - [x] 3を渡したら文字列"3"を返す
  - [x] 5 の倍数のときは数を文字列にして返す
    - [x] 5を渡したら文字列"5"を返す
  - [x] 3 と 5 両方の倍数の場合には数を文字列にして返す
    - [x] 15を渡したら文字列"15"を返す
- [x] タイプ3の場合
  - [x] 数を文字列にして返す
    - [x] 1を渡したら文字列"1"を返す
    - [x] 2を渡したら文字列"2"を返す
  - [x] 3 の倍数のときは数を文字列にして返す
    - [x] 3を渡したら文字列"3"を返す
  - [x] 5 の倍数のときは数を文字列にして返す
    - [x] 5を渡したら文字列"5"を返す
  - [x] 3 と 5 両方の倍数の場合には｢FizzBuzz｣と返す
    - [x] 15を渡したら文字列"FizzBuzz"を返す
- [x] それ以外のタイプの場合
  - [x] 例外を返す

=== ユースケース図

=== クラス図
[plantuml]
----
class FizzBuzz {
    MAX_NUMBER = 100
    FizzBuzzType type
    ArrayList list
    ArrayList generate_list()
}

class FizzBuzzType {
  TYPE_01 = 1
  TYPE_02 = 2
  TYPE_03 = 3
  FizzBuzzType {static} create()
  Boolean is_fizz()
  Boolean is_buzz()
}

class FizzBuzzType01 {
    String generate()
}

class FizzBuzzType02 {
    String generate()
}

class FizzBuzzType03 {
    String generate()
}

FizzBuzz *- FizzBuzzType
FizzBuzzType <|-- FizzBuzzType01
FizzBuzzType <|-- FizzBuzzType02
FizzBuzzType <|-- FizzBuzzType03
----

=== シーケンス図

== 開発

[source, ruby]
----
include::../../../api/index.rb[]
----

----
include::../../../api/FizzBuzz.rb[]
----

== 参照

* http://asciidoctor.org/[Asciidoctor]

* http://www.plantuml.com[PlantUML]
